# Generated by Django 3.0.7 on 2020-06-22 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import www.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cinematographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/cinematographer/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актеры, режиссеры, сценаристы, ...',
                'verbose_name_plural': 'Актеры, режиссеры, сценаристы, ...',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название фильма')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата выхода в прокат')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('budget', models.PositiveIntegerField(default=0, help_text='сумма в USD', verbose_name='Бюджет')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
                ('time', models.CharField(blank=True, max_length=30, verbose_name='Длительность')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('poster', models.ImageField(upload_to='media/films/', verbose_name='Афиша')),
                ('flag_poster', models.BooleanField(default=False, verbose_name='Показывать в афише')),
                ('description', models.TextField(blank=True, verbose_name='Сюжет')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='www.Cinematographer', verbose_name='Актеры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Category', verbose_name='Категория')),
                ('directors', models.ManyToManyField(related_name='film_director', to='www.Cinematographer', verbose_name='Режиссеры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='FilmPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=www.models.ChangeName('media/images/'), verbose_name='Изображение')),
                ('image_title', models.CharField(blank=True, max_length=100, verbose_name='Название изображения')),
                ('alt', models.CharField(blank=True, max_length=100, verbose_name='Alt')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.Film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Кадр из фильма',
                'verbose_name_plural': 'Кадры из фильма',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='film_genre', to='www.Genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='film',
            name='operators',
            field=models.ManyToManyField(related_name='film_operator', to='www.Cinematographer', verbose_name='Операторы'),
        ),
        migrations.AddField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(related_name='film_producer', to='www.Cinematographer', verbose_name='Продюсер'),
        ),
        migrations.AddField(
            model_name='film',
            name='screenwriters',
            field=models.ManyToManyField(related_name='film_screenwriter', to='www.Cinematographer', verbose_name='Сценарий'),
        ),
    ]
