# Generated by Django 3.0.7 on 2020-06-23 14:47

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='posters_jpeg',
            field=smartfields.fields.ImageField(default=1, upload_to='posters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinematographer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinematographer',
            name='image',
            field=models.ImageField(blank=True, upload_to='cinematographer/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='film_actor', to='www.Cinematographer', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='film_director', to='www.Cinematographer', verbose_name='Режиссеры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='film_genre', to='www.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='film_operator', to='www.Cinematographer', verbose_name='Операторы'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=smartfields.fields.ImageField(blank=True, upload_to='posters', verbose_name='Афиша'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='film_producer', to='www.Cinematographer', verbose_name='Продюсер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='screenwriters',
            field=models.ManyToManyField(blank=True, related_name='film_screenwriter', to='www.Cinematographer', verbose_name='Сценарий'),
        ),
        migrations.AlterField(
            model_name='filmpicture',
            name='image',
            field=models.ImageField(upload_to=www.models.ChangeName('media/pictures/'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
