# Generated by Django 3.0.7 on 2020-06-23 14:54

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20200623_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='posters_jpeg',
        ),
        migrations.AddField(
            model_name='film',
            name='poster_jpeg',
            field=smartfields.fields.ImageField(default=1, upload_to='posters/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=smartfields.fields.ImageField(blank=True, upload_to='posters/', verbose_name='Афиша'),
        ),
    ]
