# Generated by Django 3.0.7 on 2020-06-23 15:00

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_remove_film_poster_jpeg'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_jpeg',
            field=smartfields.fields.ImageField(default=1, upload_to='posters/'),
            preserve_default=False,
        ),
    ]
