# Generated by Django 3.0.7 on 2020-06-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_film_poster_jpeg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_jpeg',
        ),
    ]
