# Generated by Django 3.0.7 on 2020-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20200624_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='trailer',
        ),
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.TextField(blank=True, verbose_name='URL Видео'),
        ),
    ]
